development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: file_uploader_development
  pool: 5
  username: rails_user
  password: mint06

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: file_uploader_test
  pool: 5
  username: rails_user
  password: mint06

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: file_uploader_production
  pool: 5
  username: rails_user
  password: mint06 